config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'about', to: 'pages#about'
  get '/search', to: 'search#index'
  resources :docs
  resources :directors
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/award.rb
class Award < ApplicationRecord
  belongs_to :doc
end

app/models/director.rb
class Director < ApplicationRecord
  include PgSearch::Model
  multisearchable against: [:name]

  has_many :projects
  has_many :docs, through: :projects
  has_many :pages, inverse_of: :director, dependent: :destroy
  has_one_attached :photo
  accepts_nested_attributes_for :pages, reject_if: :all_blank, allow_destroy: true

  validates :name, presence: true, uniqueness: true
end

app/models/doc.rb
class Doc < ApplicationRecord
  include PgSearch::Model
  multisearchable against: [:name]

  has_many :projects
  has_many :directors, through: :projects
  has_many :awards, inverse_of: :doc, dependent: :destroy
  has_many :links, inverse_of: :doc, dependent: :destroy
  has_one_attached :poster
  accepts_nested_attributes_for :awards, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :links, reject_if: :all_blank, allow_destroy: true

  validates :name, presence: true, uniqueness: true
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :doc
end

app/models/page.rb
class Page < ApplicationRecord
  belongs_to :director
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :director
  belongs_to :doc

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  # protect_from_forgery

  # helper_method :current_user, :signed_in?, :is_admin?

  # def current_user
  #   @current_user ||= User.find(session[:user_id]) if session[:user_id]
  # end

  # def signed_in?
  #   !!current_user
  # end

  # def is_admin?
  #   signed_in? ? current_user.admin : false
  # end

end

app/controllers/directors_controller.rb
class DirectorsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  def index
    if params[:query].present?
      @directors = Director.where("name ILIKE ?", "%#{params[:query]}%")
    else
      @directors = Director.all
    end
  end

  def show
    @director = Director.find(params[:id])
  end

  def new
    @director = Director.new # needed to instantiate the form_for
    @director.pages.build
    @director.docs.build
  end

  def create
    @director = Director.new(director_params)
    if @director.save
      flash[:notice] = 'Director has been successfully created.'
      redirect_to directors_path(@director)
    else
      render :new
    end
  end

  def edit
    @director = Director.find(params[:id])
  end

  def update
    @director = Director.find(params[:id])
    @director.update(director_params)

    redirect_to director_path(@director)
  end

  def destroy
    @director = Director.find(params[:id])
    @director.destroy

    redirect_to directors_path
  end

  private

  def director_params
    params.require(:director)
    .permit(:name,
      :bio_short,
      :bio_long,
      :bio_source,
      :birth_year,
      :death_year,
      :photo,
      :imgcredit,
      doc_ids: [],
      pages_attributes: [:id, :description, :url, :_destroy],
      directors_attributes: [:id, :name])
  end
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  def index
    if params[:query].present?
      @docs = Doc.where("name ILIKE ?", "%#{params[:query]}%")
    else
      @docs = Doc.all
    end
  end

  def show
    @doc = Doc.find(params[:id])
  end

  def new
    @doc = Doc.new # needed to instantiate the form_for
    @doc.awards.build
    @doc.links.build
    @doc.directors.build
  end

  def create
    @doc = Doc.new(doc_params)
    if @doc.save
      flash[:notice] = 'Doc has been successfully created.'
      redirect_to docs_path(@doc)
    else
      render :new
    end
  end

  def edit
    @doc = Doc.find(params[:id])
  end

  def update
    @doc = Doc.find(params[:id])
    @doc.update(doc_params)

    redirect_to doc_path(@doc)
  end

  def destroy
    @doc = Doc.find(params[:id])
    @doc.destroy

    redirect_to docs_path
  end

  private

  def doc_params
    params.require(:doc)
    .permit(:name,
      :chinese_name,
      :year,
      :duration,
      :doc_summary_short,
      :doc_summary_long,
      :doc_summary_source,
      :trailer_link,
      :poster,
      :imgcredit,
      director_ids: [],
      awards_attributes: [:id, :name, :year, :location, :_destroy],
      links_attributes: [:id, :description, :url, :_destroy],
      directors_attributes: [:id, :name]
      )
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end

  def about
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def index
    @query = params[:query]
     redirect_to :root if @query == ''
    @results = PgSearch.multisearch(params[:query])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def video_embed(video_url)

    # REGEX EXTRACT VIDEO ID
    regex_id = /(?:youtube(?:-nocookie)?\.com\/(?:[^\/\n\s]+\/\S+\/|(?:v|e(?:mbed)?)\/|\S*?[?&]v=)|youtu\.be\/|vimeo\.com\/)([a-zA-Z0-9_-]{8,11})/
    match_id = regex_id.match(video_url)
    video_id = ""
    if match_id && !match_id[1].blank?
      video_id = match_id[1]
    end

    # REGEX EXTRACT PROVIDER - YOUTUBE OR VIMEO
    regex_prov = /(youtube|youtu\.be|vimeo)/
    match_prov = regex_prov.match(video_url)
    video_prov = ""
    if match_prov && !match_prov[1].blank?
      video_prov = case match_prov[1]
                     when "youtube"
                       :youtube
                     when "youtu.be"
                       :youtube
                     when "vimeo"
                       :vimeo
      end
    end

    case video_prov
      when :youtube
        "https://www.youtube.com/embed/#{video_id}"
      when :vimeo
        "https://player.vimeo.com/video/#{video_id}"
    end

  end
end

app/views/directors/_page_fields.html.erb
<%= f.input :description %>
    <%= f.input :url %>
<%= link_to_remove_association "remove link", f %>

app/views/directors/edit.html.erb
<%= simple_form_for @director, url: director_path do |f| %>
<%= f.label :name %>
  <p> <%= f.text_field :name %></p>
  <p> <%= f.label :bio_short %></p>
  <p> <%= f.text_field :bio_short %></p>
  <p> <%= f.label :bio_long %></p>
  <p> <%= f.text_field :bio_long %></p>
  <p> <%= f.label :bio_source %></p>
  <p> <%= f.text_field :bio_source %></p>
  <p> <%= f.label :birth_year %></p>
  <p> <%= f.text_field :birth_year %></p>
  <p> <%= f.label :death_year %></p>
  <p> <%= f.text_field :death_year %></p>
   <p><%= f.collection_check_boxes :doc_ids, Doc.all, :id, :name, multiple: true%></p>


  <p><%= f.file_field :photo, as: :file %></p>
    <p><%= f.label :imgcredit %></p>
  <p><%= f.text_field :imgcredit %></p>


  <h2>Useful Links</h2>
  <%= f.simple_fields_for :pages do |page| %>
  <P>Link</P>
  <p> <%= page.text_field :description %></p>
  <p> <%= page.text_field :url %></p>
<% end %>
<%= simple_fields_for :pages, @director.pages.build do |page| %>
<div class="links">
  <%= link_to_add_association 'add link', f, :pages %>
</div>
<% end %>








  <p> <%= f.button :submit %></p>
<% end %>

app/views/directors/index.html.erb
  <div class="header-text">
    <p>documentaries</p>
    <h1>By author</h1>
  </div>
  <div class="grid-container">
    <div class="index-search">
      <%= form_tag directors_path, method: :get do %>
        <%= text_field_tag :query,
          params[:query],
          class: "form-control",
          placeholder: "Search"
        %>
      <% end %>
    </div>

    <div class="section-authors">
      <% @directors = @directors.order("name ASC").group_by{ |u| u.name[0] }  %>
      <% @directors.each do |letter, directors| %>
        <h1 class="abc-title"><%= letter %></h1>
        <ul class="authors-list">
           <% directors.each do |director| %>
          <li> <%= link_to director.name, director_path(director) %>
            <% if current_user %>
              <% if current_user.admin? %>
            <p> <%= link_to "Edit", edit_director_path(director) %> <%= link_to "Delete", director_path(director), method: :delete, data: { confirm: 'Are you sure you want to delete this item?'} %></p>
              <% end %>
            <% end %>
            </li>
        <% end %>
        </ul>
      <% end %>
    </div>
  </div>

app/views/directors/new.html.erb
  <div class="container">
    <% if @director.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@director.errors.count, "error") %>
          prohibited this director from being saved :
        </h2>
        <ul>
          <% @director.errors.full_messages.each do |msg|%>
          <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="form-group">
      <%= simple_form_for @director, url: directors_path do |f| %>
        <%= f.input :name %>
        <%= f.input :bio_short %>
        <%= f.input :bio_long %>
        <%= f.input :bio_source %>
        <%= f.input :birth_year %>
        <%= f.input :death_year %>
        <%= f.collection_check_boxes :doc_ids, Doc.all, :id, :name, multiple: true%>

         <%= f.input :photo, as: :file %>
         <%= f.input :imgcredit %>
      <h2>To go further</h2>
      <%= f.simple_fields_for :pages do |page| %>
      <%= render 'page_fields', f: page %>
      <% end %>
      <div class="links">
        <%= link_to_add_association 'add link', f, :pages %>
      </div>
        <%= f.button :submit %>
      <% end %>
    </div>
   </div>

app/views/directors/show.html.erb
<div class="padding-top">
  <div class="container">
      <div class="section-author">
        <% if @director.photo.present? %>
          <% if @director.imgcredit.present? %>
            <%= cl_image_tag @director.photo.key,
              overlay: {font_family:"Arial", :font_size=>12, :text=>@director.imgcredit},
              gravity: :south_east,
              x:5,
              y:5,
              color: '#fff',
              class:"author-photo" %>
          <% else %>
            <%= cl_image_tag @director.photo.key, class:"author-photo" %>
          <% end %>
        <% end %>
        <div class="section-author-text">
          <h1> <%= @director.name %> </h1>
            <div class="doc-summary">
              <p><%= @director.bio_short %></p>
              <p><%= @director.bio_long %>

              <span>Source <%= @director.bio_source %></span>
              </p>
            </div>
          </div>
        </div>
        <div class="section-author-filmo">
          <h2 class="section-author-filmo-title">Filmography</h2>
          <div class="section-author-filmo-list">
            <ul>
              <% @director.docs.each do |doc| %>
                <li><%= link_to doc.name, doc_path(doc) %> <% if doc.year? %>(<%= doc.year %>) <% end %></li>
              <% end %>
            </ul>
          </div>
        </div>
    </div>


    <div class="doc-more-infos">
      <div class="container">
        <h2>To go further...</h2>
        <div class="doc-links">
          <ul class="doc-links-list">
            <% @director.pages.each do |page| %>
            <li>
              <a href=<%= page.url %>><%= page.description %></a>
            </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
    <div class="container">
      <% if current_user %>
        <% if current_user.admin? %>
          <div> <%= link_to "Edit", edit_director_path(@director) %>
                <%= link_to "Delete", director_path(@director), method: :delete %>
          </div>
        <% end %>
      <% end %>
    </div>
</div>

app/views/docs/_award_fields.html.erb
    <%= f.input :name %>
    <%= f.input :year %>
    <%= f.input :location %>
    <%= link_to_remove_association "remove award", f %>

app/views/docs/_link_fields.html.erb
    <%= f.input :description %>
    <%= f.input :url %>
    <%= link_to_remove_association "remove link", f %>

app/views/docs/edit.html.erb
<div class="page">
  <div class="container">

<%= simple_form_for @doc, url: doc_path do |f| %>
<p><%= f.label :name %></p>
  <p> <%= f.text_field :name %></p>
<p> <%= f.label :chinese_name %></p>
  <p> <%= f.text_field :chinese_name %></p>
  <p> <%= f.label :year %></p>
  <p> <%= f.text_field :year %></p>
  <p> <%= f.label :duration %></p>
  <p> <%= f.text_field :duration %></p>
  <p> <%= f.label :doc_summary_short %></p>
  <p> <%= f.text_field :doc_summary_short %></p>
  <p> <%= f.label :doc_summary_long %></p>
  <p> <%= f.text_field :doc_summary_long %></p>
  <p> <%= f.label :doc_summary_source %></p>
  <p> <%= f.text_field :doc_summary_source %></p>
  <p> <%= f.label :trailer_link %></p>
  <p> <%= f.text_field :trailer_link %></p>
  <p><%= f.file_field :poster, as: :file %></p>
  <p><%= f.label :imgcredit %></p>
  <p><%= f.text_field :imgcredit %></p>
   <p><%= f.collection_check_boxes :director_ids, Director.all, :id, :name, multiple: true%></p>

  <h3>AWARDS</h3>
  <p> <%= f.simple_fields_for :awards do |award| %></p>
  <p>Award</p>
  <p> <%= award.text_field :name %> </p>
  <p> <%= award.text_field :year %></p>
  <p> <%= award.text_field :location %></p>
  <% end %>
  <%= f.fields_for :awards, @doc.awards.build do |award| %>
  <div class='links'>
  <%= link_to_add_association 'add award', f, :awards %>
  </div>
  <% end %>

<h2>Useful Links</h2>
  <%= f.simple_fields_for :links do |link| %>
  <P>Link</P>
  <p> <%= link.text_field :description %></p>
  <p> <%= link.text_field :url %></p>
<% end %>
<%= simple_fields_for :links, @doc.links.build do |link| %>
<div class="links">
  <%= link_to_add_association 'add link', f, :links %>
</div>
<% end %>


  <p> <%= f.button :submit %></p>
<% end %>
</div>
<!-- </div> -->

app/views/docs/index.html.erb
<div class="header-text">
  <p>documentaries</p>
  <h1>By title</h1>
</div>
<div class="grid-container">
  <div class="index-search">
    <%= form_tag docs_path, method: :get do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Search"
      %>
    <% end %>
  </div>
  <div class="section-authors">
    <% @docs = @docs.order("name ASC").group_by{ |u| u.name[0] }  %>
    <% @docs.each do |letter, docs| %>
      <h1 class="abc-title"><%= letter %></h1>
      <ul class="authors-list">
         <% docs.each do |doc| %>
        <li> <%= link_to doc.name, doc_path(doc) %>
          <% if current_user %>
            <% if current_user.admin? %>
              <p> <%= link_to "Edit", edit_doc_path(doc) %> <%= link_to "Delete", doc_path(doc), method: :delete, data: { confirm: 'Are you sure you want to delete this item?'} %></p>
            <% end %>
          <% end %>
          </li>
      <% end %>
      </ul>
    <% end %>
  </div>
</div>

app/views/docs/show.html.erb
<div class="padding-top">
  <div class="container">
      <div class="grid-doc">
        <div>
          <h2 class="doc-title">
            <%= @doc.name %>
          </h2>
          <h3 class="doc-author">
            <% if @doc.directors.count == 1 %>
              by <% @doc.directors.each do |dir| %>
                <%= link_to dir.name, director_path(dir) %>
                <% end %>
              <% else %>
                by <%@doc.directors.each do |dir| %>
                  <%= link_to dir.name, director_path(dir) %><%= ", " unless dir == @doc.directors.last %>
              <% end %>
            <% end %>
          </h3>

          <div class="doc-infos">
            <div class="doc-year flex-center"><ion-icon class="doc-icon" name="calendar-number-outline"></ion-icon><%= @doc.year  %></div>
            <div class="doc-duration flex-center"><ion-icon class="doc-icon" name="time-outline"></ion-icon><%= @doc.duration  %></div>
            <div class="doc-chinese-name"><%= @doc.chinese_name %></div>
          </div>
        </div>
        <div class="grid-item-poster">
          <% if @doc.poster.present? %>
            <% if @doc.imgcredit.present? %>
              <%= cl_image_tag @doc.poster.key,
              overlay: {font_family:"Arial", :font_size=>12, :text=>@doc.imgcredit},
              gravity: :south_east,
              x:5,
              y:5,
              color: '#fff',
              class:"doc-poster" %>
            <% else %>
              <%= cl_image_tag @doc.poster.key, class:"doc-poster" %>
            <% end %>
          <% end %>
        </div>
        <div class="doc-summary">
          <div class="doc-summary-short">
            <p>
              <%= @doc.doc_summary_short  %>
              <!-- <ion-icon class="plus-icon" name="add-circle-outline"></ion-icon> -->
            </p>
          </div>
          <div class="doc-summary-long">
            <p>
              <%= @doc.doc_summary_long  %>
            </p>
            <%= @doc.doc_summary_source  %>
          </div>
        </div>
        <div class="doc-awards">
          <h3>Awards</h3>
          <div class="doc-awards-short">
            <ul class="doc-awards-list">
              <% @doc.awards.each do |award| %>
              <li><ion-icon class="star-icon" name="star-outline"></ion-icon> <%= award.name %>, <%= award.year %>, <%= award.location %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>

        <div class="doc-trailer">
          <h3>Official Trailer</h3>

          <!-- <div class="embed-responsive embed-responsive-16by9"> -->
            <iframe class="embed-responsive-item" src="<%= video_embed(@doc.trailer_link) %>" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
          <!-- </div> -->
        </div>
  </div>

  <div class="doc-more-infos">
    <div class="container">
      <h2>To go further...</h2>
      <div class="doc-links">
        <ul class="doc-links-list">
          <% @doc.links.each do |link| %>
          <li>
            <a href=<%= link.url %>><%= link.description %></a>
          </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
  <div class="container">
    <% if current_user %>
        <% if current_user.admin? %>
          <div> <%= link_to "Edit", edit_doc_path(@doc) %>
                <%= link_to "Delete", doc_path(@doc), method: :delete %>
          </div>
        <% end %>
    <% end %>
  </div>
</div>
<!-- </div> -->

app/views/docs/show2.html.erb
<div class="page">
<!--   <div class="header-text">
    <p>documentaries</p>
    <h1>By title</h1>
  </div> -->
  <div class="grid-container">
    <div class="input-box">
      <input type="text" class="form-control">
      <i class="fa fa-search"></i>
    </div>
    <div class="section-authors">
      <% @docs = Doc.order("name ASC").group_by{ |u| u.name[0] }  %>
      <% @docs.each do |letter, docs| %>
        <h1 class="abc-title"><%= letter %></h1>
        <ul class="authors-list">
           <% docs.each do |doc| %>
          <li> <%= link_to doc.name, doc_path(doc) %>
            <p> <%= link_to "Edit", edit_doc_path(doc) %> <%= link_to "Delete", doc_path(doc), method: :delete %></p>
            </li>
        <% end %>
        </ul>
      <% end %>
    </div>
  <!-- </div> -->
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
    <title>CHINADocsDb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <!-- <div class="site-content"> -->
    <%= yield %>
    <!-- </div> -->
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home-v1.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>
<%= cl_image_tag("klnjkdalc8srgygexkqm",
      width: 400, height: 300, crop: :fill) %>

      <p>Now is <%= Time.now %></p>
      <%= link_to "Know more about us", about_path %>

app/views/pages/home.html.erb
  <div class="hero fixed-top">
    <%= simple_form_for :search, url: search_path, method: "GET" do |f| %>
      <div class="d-flex my-search">
        <%= text_field_tag :query, params[:query], class: "form-control me-2", placeholder: "Search" %>
        <%= f.button :submit, 'Search', class: "btn btn-danger btn-input" %>
      </div>
    <% end %>
  </div>


  <div class="sections">
    <div class="sections-flexbox">
      <%= link_to directors_path  do %>
        <div class="section-findby section-findby-author">
            <div class="container flexbox-center">
                <div class="findby-box">
                  <h2>Documentaries</h2>
                  <p>by author</p>
                </div>
            </div>
        </div>
      <% end %>

      <%= link_to docs_path do %>
        <div class="section-findby section-findby-title">
            <div class="container flexbox-center">
                <div class="findby-box">
                  <h2>Documentaries</h2>
                  <p>by title</p>
                </div>
            </div>
        </div>
      <% end %>
    </div>

<!--   <div class="section-featured">
    <div class="container">
      <h1 class="featured-title">Featured this week</h1>
      <div class="featured-box">
        <%# doc = Doc.find(Doc.ids.sample) %>
          <h2><%#= doc.name %></h2>
          <a class="featured-link-author" href="#"><p>by <%# doc.directors.each do |director| %>
            <%#= link_to director.name, director_path(director) %>
            <%#= director.name %> <%# end %>
          </p></a>
          <a class="featured-link-movie" href="#">
            <%#= image_tag "behemoth.jpg", alt: "Behemoth Poster", class: "img_preview" %>
          </a>
      </div>
    </div>
  </div> -->
</div>

app/views/search/index.html.erb
<div class="header-text">
  <p>search results for</p>
  <h1><%= @query %></h1>
</div>
<div class="grid-container">
  <div class="section-authors search-results">
    <% @results.each do |letter, results| %>
        <ul class="authors-list">
          <% @results.each do |result| %>
            <li><%= link_to result.searchable.name, "../#{(result.searchable.class).to_s.downcase!.pluralize}/#{result.searchable.id}" %>
            </li>
            <% if current_user %>
              <% if current_user.admin? %>
                <p> <%= link_to "Edit", edit_doc_path(result.searchable) %> <%= link_to "Delete", doc_path(result.searchable), method: :delete, data: { confirm: 'Are you sure you want to delete this item?'} %></p>
              <% end %>
            <% end %>
          <% end %>
        </ul>
    <% end %>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="container">
  <footer class="py-3 my-4">
    <p class="text-center text-muted">© 2022 China Documentaries Database</p>
  </footer>
</div>

app/views/shared/_navbar.html.erb
  <div class="header">
    <div class="header-top">
      <nav class="navbar navbar-expand-lg navbar-top navbar-light fixed-top">
        <div class="container-fluid">
          <%= link_to "/" do %>
            <%= image_tag "CDD-logo.png", alt: "China Documentaries Database logo", class: "logo" %>
          <% end %>
          <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
            <div class="offcanvas-header">
            <%= image_tag "CDD-logo.png", alt: "China Documentaries Database logo", class: "logo" %>

              <!-- <h5 class="offcanvas-title" id="offcanvasNavbarLabel">Offcanvas</h5> -->
              <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
            </div>
            <div class="offcanvas-body">
              <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                <li class="nav-item">
                  <%= link_to "Home", "/", class: "nav-link active" %>
                  <!-- <a class="nav-link active" aria-current="page" href="#">Home</a> -->
                </li>
                <li class="nav-item">
                  <%= link_to "Find by Author", "/directors", class: "nav-link" %>
                  <!-- <a class="nav-link" href="#">Link</a> -->
                </li>
                <li class="nav-item">
                  <%= link_to "Find by Title", "/docs", class: "nav-link" %>
                  <!-- <a class="nav-link" href="#">Link</a> -->
                </li>
                <li class="nav-item">
                  <% doc = Doc.find(Doc.ids.sample) %>
                  <%= link_to "Random documentary", doc_path(doc), class: "nav-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to "About", about_path, class: "nav-link" %>
                </li>
                <% if !current_user %>
                  <li class="nav-item">
                    <%#= link_to "Login", new_user_session_path, class: "nav-link" %>
                  </li>
                  <% else %>
                <li class="nav-item">
                  <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
                </li>
                <% end %>
                <!-- <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="offcanvasNavbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Dropdown
                  </a>
                  <ul class="dropdown-menu" aria-labelledby="offcanvasNavbarDropdown">
                    <li><a class="dropdown-item" href="#">Action</a></li>
                    <li><a class="dropdown-item" href="#">Another action</a></li>
                    <li>
                      <hr class="dropdown-divider">
                    </li>
                    <li><a class="dropdown-item" href="#">Something else here</a></li>
                  </ul>
                </li> -->
              </ul>
              <form class="d-flex">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-danger" type="submit">Search</button>
              </form>
              <% if current_user %>
                <% if current_user.admin? %>
                  <ul class="navbar-nav justify-content-end flex-grow-1 pe-3 admin-menu">
                    <li class="nav-item">
                      <%= link_to "Create a new documentary", "/docs/new", class: "nav-link" %>
                    </li>
                    <li class="nav-item">
                      <%= link_to "Create a new director", "/directors/new", class: "nav-link" %>
                    </li>
                  </ul>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </nav>
    </div>
  </div>